import test from 'node:test';
import assert from 'node:assert/strict';
import {createSession,restoreSession} from '../dist/game/session.js';
const act=(s,command)=>{const r=s.dispatch({expectedRevision:s.getSnapshot().revision,command});assert.equal(r.accepted,true,r.errors?.[0]?.message);};
test('departure is explicit; supply and preparation cannot move to another node',()=>{
 const s=createSession(1,{nodePool:['N01','N02']});assert.equal(s.getSnapshot().phase,'VoyageNavigation');const target=s.getSnapshot().candidates[0];const before=s.getSnapshot();assert.equal(s.preview({type:'DrawSpring'}).allowed,false);assert.equal(s.preview({type:'SubmitVoyage',candidateId:target.id}).allowed,true);assert.deepEqual(s.getSnapshot(),before);
 act(s,{type:'SubmitVoyage',candidateId:target.id});assert.equal(s.getSnapshot().phase,'VoyageSupply');assert.equal(s.getSnapshot().node.nodeId,target.nodeId);assert.equal(s.getSnapshot().candidates.length,0);act(s,{type:'DrawSpring'});assert.equal(s.getSnapshot().phase,'VoyagePreparation');assert.equal(s.preview({type:'SubmitVoyage',candidateId:target.id}).allowed,false);act(s,{type:'EnterNode'});assert.equal(s.getSnapshot().phase,'NodeResolution');
});
test('overflow discard blocks navigation until the last required card; no sixth voyage',()=>{
 const save=createSession(1,{nodePool:['N01','N02']}).exportSave();save.state.phase='VoyageAction';save.state.node={nodeId:'N01'};save.state.candidates=[];save.state.hand=Array.from({length:12},(_,i)=>({id:'extra-'+i,definitionId:'C01',age:0,temporary:false}));const s=restoreSession(save);act(s,{type:'EndVoyageAction'});assert.equal(s.getSnapshot().phase,'VoyageDiscard');assert.equal(s.getSnapshot().voyageIndex,1);const before=s.getSnapshot();assert.equal(s.preview({type:'SubmitVoyage',candidateId:'missing'}).allowed,false);assert.equal(s.preview({type:'FinishDiscard'}).allowed,false);assert.deepEqual(s.getSnapshot(),before);act(s,{type:'DiscardCards',cardIds:['extra-0']});assert.equal(s.getSnapshot().phase,'VoyageDiscard');act(s,{type:'DiscardCards',cardIds:['extra-1']});assert.equal(s.getSnapshot().phase,'VoyageNavigation');assert.equal(s.getSnapshot().voyageIndex,2);assert.ok(s.getSnapshot().candidates.length>=2);assert.equal(s.getSnapshot().hand.length,10);
 const final=s.exportSave();final.state.phase='VoyageAction';final.state.voyageIndex=5;final.state.candidates=[];const end=restoreSession(final);act(end,{type:'EndVoyageAction'});assert.equal(end.getSnapshot().phase,'Completed');assert.equal(end.getSnapshot().candidates.length,0);
});
test('navigation tools and anchor preserve fees; save replay does not reroll nodes or spring cards',()=>{
 const s=createSession(4,{nodePool:['N01','N02'],initialCards:['C22','C24','C23','C10','C01','C04','C08']});
 const old=s.exportSave();old.contentVersion='first-layer-v2';assert.throws(()=>restoreSession(old),/版本/);
 const restored=restoreSession(s.exportSave());assert.deepEqual(restored.getSnapshot(),s.getSnapshot());
 for(const id of ['C22','C24']){const command={type:'PlayCard',cardId:s.getSnapshot().hand.find(c=>c.definitionId===id).id,target:{kind:'candidates'}};act(s,command);act(restored,command);assert.deepEqual(restored.getSnapshot(),s.getSnapshot());}
 const move={type:'SubmitVoyage',candidateId:s.getSnapshot().candidates.find(c=>c.nodeId==='N01').id,protectionCardId:s.getSnapshot().hand.find(c=>c.definitionId==='C23').id};act(s,move);act(restored,move);assert.equal(s.getSnapshot().ap,0);assert.equal(s.getSnapshot().node.protected,true);act(s,{type:'DrawSpring'});act(restored,{type:'DrawSpring'});assert.equal(s.getSnapshot().ap,0);assert.deepEqual(restored.getSnapshot(),s.getSnapshot());act(s,{type:'EnterNode'});act(s,{type:'ResolveNodeOption',optionId:'0'});assert.equal(s.getSnapshot().phase,'VoyageNavigation');assert.equal(s.getSnapshot().voyageIndex,2);
});
test('entering a chosen battle preserves its generated enemies; battle discard stays in the same voyage',()=>{
 const s=createSession(5,{nodePool:['N01','N05']});const target=s.getSnapshot().candidates.find(c=>c.nodeId==='N05');act(s,{type:'SubmitVoyage',candidateId:target.id});act(s,{type:'DrawSpring'});act(s,{type:'EnterNode'});assert.equal(s.getSnapshot().phase,'BattleAction');assert.equal(s.getSnapshot().enemies.length,target.enemies.length);assert.equal(s.getSnapshot().ap,3);act(s,{type:'EndBattleTurn'});act(s,{type:'ChooseSupply',definitionId:'T01'});act(s,{type:'EndBattleTurn'});assert.equal(s.getSnapshot().phase,'BattleDiscard');act(s,{type:'DiscardCards',cardIds:[s.getSnapshot().hand.find(c=>c.definitionId==='T01').id]});assert.equal(s.getSnapshot().phase,'BattleSupply');assert.equal(s.getSnapshot().voyageIndex,1);assert.equal(s.getSnapshot().candidates.length,0);
});
