import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from '../dist/vendor/three.module.min.js';
import {createRaftResources} from '../dist/presentation/models/raft.js';
import {ROOT_CONFIG} from '../dist/presentation/models/raft-root.js';
import {createRaftPresenter} from '../dist/presentation/scene/raft-presenter.js';
const view=()=>({cells:[{id:'a',x:0,z:0,state:'intact',label:'1-1'},{id:'b',x:1,z:0,state:'intact',label:'2-1'}],units:[],defense:[{index:0,cellId:'a'}],logistics:[{index:0,cellId:'b'}]});
test('presenter follows arbitrary added/removed coordinates, lost cells leave no deck or pick proxy',()=>{
 const resources=createRaftResources();const presenter=createRaftPresenter({resources});const state=view();presenter.sync(state);assert.equal(presenter.cells.size,2);state.cells.push({id:'c',x:-1,z:1,state:'damaged',label:'0-2'});presenter.sync(state);assert.equal(presenter.cells.size,3);assert.equal(presenter.cells.get('c').panel.root.position.x,-2.3);assert.equal(presenter.cells.get('c').panel.root.userData.state,'damaged');assert.equal(presenter.getPickMeshes().length,3);
 state.cells[1].state='lost';presenter.sync(state);assert.equal(presenter.cells.get('b').panel.root.visible,false);assert.equal(presenter.getPickMeshes().length,2);state.cells=state.cells.filter(c=>c.id!=='c');presenter.sync(state);assert.equal(presenter.cells.size,2);assert.equal(presenter.getPickMeshes().length,1);presenter.dispose();assert.equal(resources.disposed,false);resources.dispose();
});
test('cell text maps units, disabled state, wrecks, products and empty roles without changing view',()=>{
 const resources=createRaftResources();const labels=[];const presenter=createRaftPresenter({resources,createLabel:()=>{const root=new THREE.Group();const label={root,lines:[],update(lines){this.lines=lines},dispose(){root.removeFromParent()}};labels.push(label);return label;}});const state=view();state.units=[{id:'net',definitionId:'C20',cellId:'b',structure:4,operational:true,progress:2,stored:{definitionId:'C09'}}];const copy=structuredClone(state);presenter.sync(state);assert.deepEqual(state,copy);assert.ok(presenter.cells.get('b').label.lines.join(' ').includes('捕捞网'));assert.ok(presenter.cells.get('b').label.lines.join(' ').includes('鲜鱼'));assert.ok(presenter.cells.get('a').label.lines.join(' ').includes('防卫'));state.cells[1].state='damaged';state.units[0].operational=false;presenter.sync(state);assert.ok(presenter.cells.get('b').label.lines.join(' ').includes('停用'));state.units[0].structure=0;presenter.sync(state);assert.ok(presenter.cells.get('b').label.lines.join(' ').includes('残骸'));presenter.dispose();resources.dispose();
});
test('decorative root stays outside playable cells and auto-fit shrinks expanded bounds without changing state',()=>{
 const resources=createRaftResources();const presenter=createRaftPresenter({resources});const small=view();presenter.sync(small);const first=presenter.fit.scale;assert.ok(presenter.decorations.root.position.z<Math.min(...small.cells.map(c=>c.z))*2.25-1.125);assert.equal(presenter.decorations.root.userData.functional,false);const bigger=view();bigger.cells=Array.from({length:40},(_,i)=>({id:'tile-'+i,x:i%8,z:Math.floor(i/8),state:'intact'}));presenter.sync(bigger);assert.ok(presenter.fit.scale<first);assert.ok(presenter.fit.width*presenter.fit.scale<=10.6);presenter.dispose();resources.dispose();
});
test('offset grids fit their own bounds and repaired cells regain picking',()=>{
 const resources=createRaftResources(),presenter=createRaftPresenter({resources});const state=view();state.cells=state.cells.map(c=>({...c,x:c.x+10,z:c.z+10}));presenter.sync(state);assert.ok(Math.abs(presenter.fit.width-Math.max(4.6,ROOT_CONFIG.width))<1e-9);state.cells[0].state='lost';presenter.sync(state);assert.equal(presenter.getPickMeshes().length,1);state.cells[0].state='intact';presenter.sync(state);assert.equal(presenter.getPickMeshes().length,2);presenter.dispose();presenter.dispose();assert.equal(resources.disposed,false);resources.dispose();
});
